title: "micro_analyze"
output: html_document
date: "2026-02-26"
```{r}

setwd("~/Desktop/wiscam_microscopy/data/rt_basidiospore") #set your working directory
setwd("~/Desktop/wiscam_microscopy/data/rt_basidiospore/basidiospore_by_specimen")
getwd() #use to see what your current working directory is
#rename each csv to spore30181, etc for easier coding
spores30181 <- read.csv("30181_basidiospore.csv")
spores30182 <- read.csv("30182_basidiospore.csv")
spores30183 <- read.csv("30183_basidiospore.csv")
spores30184 <- read.csv("30184_basidiospore.csv")
spores30185 <- read.csv("30185_basidiospore.csv")
spores30186 <- read.csv("30186_basidiospore.csv")
spores30187 <- read.csv("30187_basidiospore.csv")
spores30188 <- read.csv("30188_basidiospore.csv")
spores30189 <- read.csv("30189_basidiospore.csv")
spores30190 <- read.csv("30190_basidiospore.csv")
spores30191 <- read.csv("30191_basidiospore.csv")
spores30192 <- read.csv("30192_basidiospore.csv")
spores30193 <- read.csv("30193_basidiospore.csv")
spores30194 <- read.csv("30194_basidiospore.csv")
spores30195 <- read.csv("30195_basidiospore.csv")
spores30196 <- read.csv("30196_basidiospore.csv")
spores30197 <- read.csv("30197_basidiospore.csv")
spores30198 <- read.csv("30198_basidiospore.csv")
spores30199 <- read.csv("30199_basidiospore.csv")
spores30201 <- read.csv("30201_basidiospore.csv")
spores30202 <- read.csv("30202_basidiospore.csv")
spores30203 <- read.csv("30203_basidiospore.csv")
spores30204 <- read.csv("30204_basidiospore.csv")
spores30205 <- read.csv("30205_basidiospore.csv")
spores30206 <- read.csv("30206_basidiospore.csv")
spores30207 <- read.csv("30207_basidiospore.csv")
spores30208 <- read.csv("30208_basidiospore.csv")
spores30209 <- read.csv("30209_basidiospore.csv")
spores30212 <- read.csv("30212_basidiospore.csv")
spores30213 <- read.csv("30213_basidiospore.csv")
spores30214 <- read.csv("30214_basidiospore.csv")
spores30215 <- read.csv("30215_basidiospore.csv")
spores30221 <- read.csv("30221_basidiospore.csv")
spores30222 <- read.csv("30222_basidiospore.csv")
spores30226 <- read.csv("30226_basidiospore.csv")
spores30230 <- read.csv("30230_basidiospore.csv")
spores30238 <- read.csv("30238_basidiospore.csv")
spores30239 <- read.csv("30239_basidiospore.csv")
spores30244 <- read.csv("30244_basidiospore.csv")
spores30249 <- read.csv("30249_basidiospore.csv")
spores30300 <- read.csv("30300_basidiospore.csv")
spores30295 <- read.csv("30295_basidiospore.csv")
spores30276 <- read.csv("30276_basidiospore.csv")
spores30274 <- read.csv("30274_basidiospore.csv")
spores30248 <- read.csv("30248_basidiospore.csv")
spores30245 <- read.csv("30245_basidiospore.csv")


# $Sample to add new column with speices ID to each basidiospore measurement
spores30181$Sample <- "30181"
spores30182$Sample <- "30182"
spores30183$Sample <- "30183"
spores30184$Sample <- "30184"
spores30185$Sample <- "30185"
spores30186$Sample <- "30186"
spores30187$Sample <- "30187"
spores30188$Sample <- "30188"
spores30189$Sample <- "30189"
spores30190$Sample <- "30190"
spores30191$Sample <- "30191"
spores30192$Sample <- "30192"
spores30193$Sample <- "30193"
spores30194$Sample <- "30194"
spores30195$Sample <- "30195"
spores30196$Sample <- "30196"
spores30197$Sample <- "30197"
spores30198$Sample <- "30198"
spores30199$Sample <- "30199"
spores30201$Sample <- "30201"
spores30202$Sample <- "30202"
spores30203$Sample <- "30203"
spores30204$Sample <- "30204"
spores30205$Sample <- "30205"
spores30206$Sample <- "30206"
spores30207$Sample <- "30207"
spores30208$Sample <- "30208"
spores30209$Sample <- "30209"
spores30212$Sample <- "30212"
spores30213$Sample <- "30213"
spores30214$Sample <- "30214"
spores30215$Sample <- "30215"
spores30221$Sample <- "30221"
spores30222$Sample <- "30222"
spores30226$Sample <- "30226"
spores30230$Sample <- "30230"
spores30238$Sample <- "30238"
spores30239$Sample <- "30239"
spores30244$Sample <- "30244"
spores30249$Sample <- "30249"
spores30300$Sample <- "30300"
spores30295$Sample <- "30295"
spores30276$Sample <- "30276"
spores30274$Sample <- "30274"
spores30248$Sample <- "30248"
spores30245$Sample <- "30245"

str(spores30181) #sanity check to make sure data loaded

head(spores30181) #sanity check to make sure data loaded

#combines each specimen to one graph
all_spores <- rbind(spores30181, spores30182, spores30183, spores30184, spores30185, spores30186, spores30187, spores30188, spores30189, spores30190, spores30191, spores30192, spores30193, spores30194, spores30195, spores30196, spores30197, spores30198, spores30199, spores30201, spores30202, spores30203, spores30204, spores30205, spores30206, spores30207, spores30208, spores30209, spores30212, spores30213, spores30214, spores30215, spores30221, spores30222, spores30226, spores30230, spores30238, spores30239, spores30244, spores30249, spores30300, spores30295, spores30276, spores30274, spores30248, spores30245)
library(ggplot2)

#groups each specimen by section
group_map <- c(
  "30181"="Phalloidae", "30182"="Phalloidae", "30183"="Roanokensis",
  "30184"="Phalloidae", "30185"="Vaginatae", "30186"="Vaginatae",
  "30187"="Phalloidae", "30188"="Vaginatae", "30189"="Vaginatae",
  "30190"="Amanita", "30191"="Amanita", "30192"="Amanita",
  "30193"="Vaginatae", "30194"="Vaginatae", "30195"="Phalloidae",
  "30196"="Amanita", "30197"="Amanita", "30198"="Vaginatae",
  "30199"="Phalloidae", "30201"="Validae", "30202"="Validae",
  "30203"="Phalloidae", "30204"="Phalloidae", "30205"="Validae",
  "30206"="Validae", "30207"="Validae", "30208"="Validae",
  "30209"="Phalloidae", "30212"="Amidella", "30213"="Validae",
  "30214"="Validae", "30215"="Vaginatae",
  "30221"="Amanita", "30222"="Amanita", "30226"="Amanita",
  "30230"="Validae", "30238"="Validae", "30239"="Ceasareae",
  "30244"="Vaginatae", "30249"="Amanita", "30300"="Amidella", "30295"="Ceasareae", "30276"="Validae", "30274"="Amidella", "30248"="Validae", "30245"="Vaginatae"
)
all_spores$Group <- group_map[all_spores$Sample]


plot <- ggplot(all_spores, aes(x = Width, y = Length, fill = Group)) +
  geom_jitter(shape = 21, size = 2, alpha = 0.7, width = 0.25, height = 0.25) +

  #formating
  scale_fill_manual(
    name = "Section",
    values = c(
      "Roanokensis"="magenta",
      "Phalloidae"="blue",
      "Vaginatae"="yellow",
      "Amanita"="red",
      "Validae"="green",
      "Ceasareae"="orange",
      "Amidella"="purple"
    ),
      aesthetics = "fill"
  ) +
  guides(color = "none") +
  xlim(0, 20) +
  ylim(0, 20) +
  theme_minimal() +
  labs(
    title = "Basidiospore Measurements",
    x = "Width (µm)",
    y = "Length (µm)"
  )

plot (plot)

#ggsave("basidiospore_measurementes_20.png", plot, width = 10, height = 7, dpi = 300) to get .png file

```

```{r}
library(dplyr)
library(ggplot2)

# Count number of spores per section
section_counts <- all_spores %>%
  group_by(Group) %>%
  summarise(n_spores = n())

# (Optional) sanity check
table(all_spores$Group, useNA = "ifany")

# Bar plot
bar_plot <- ggplot(section_counts, aes(x = Group, y = n_spores, fill = Group)) +
  geom_col(color = "black", width = 0.7) +
  scale_fill_manual(
    values = c(
      "Roanokensis"="magenta",
      "Phalloidae"="blue",
      "Vaginatae"="yellow",
      "Amanita"="red",
      "Validae"="green",
      "Ceasareae"="orange",
      "Amidella"="purple"
    )
  ) +
  labs(
    title = "Number of Basidiospore Measurements per Section",
    x = "Section",
    y = "Number of Measurements"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

bar_plot


```

```{r}
library(dplyr)
library(ggplot2)
setwd("~/Desktop/wiscam_microscopy/data/rt_basidiospore")

# 1. Load species lookup table
species_lookup <- read.csv("basidiospore.csv", stringsAsFactors = FALSE)

# 2. Rename specimen_id to Sample so it matches all_spores
species_lookup <- species_lookup %>%
  rename(Sample = specimen_id)

# 3. Ensure Sample is character
species_lookup$Sample <- as.character(species_lookup$Sample)

# 4. Merge species names into the main dataset
all_spores2 <- all_spores %>%
  left_join(species_lookup, by = "Sample")

# 5. Clean species names into "A. species" format
all_spores2$Species_clean <- sub("^Amanita ", "A. ", all_spores2$species)


# 6. Count spores per species (combining repeated specimens)
species_counts <- all_spores2 %>%
  group_by(Species_clean, Group) %>%
  summarise(n_spores = n(), .groups = "drop")

# 7. Sort species by section (Group), then alphabetically within section
species_counts$Species_clean <- factor(
  species_counts$Species_clean,
  levels = species_counts %>%
    arrange(Group, Species_clean) %>%
    pull(Species_clean)
)

# 8. Bar plot by species, color-coded by section
species_plot <- ggplot(species_counts,
                       aes(x = Species_clean,
                           y = n_spores,
                           fill = Group)) +
  geom_col(color = "black") +
  scale_fill_manual(
    values = c(
      "Roanokensis"="magenta",
      "Phalloidae"="blue",
      "Vaginatae"="yellow",
      "Amanita"="red",
      "Validae"="green",
      "Ceasareae"="orange",
      "Amidella"="purple"
    )
  ) +
  labs(
    title = "Total Basidiospore Measurements per Species",
    x = "Species",
    y = "Number of Measurements"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "italic")
  )

species_plot

```
#add a ceasarea, a phalloidae, 2 Amidella, sp 61, solaniolens, rubescense, brunesense, fulva

```{r}
library(dplyr)
library(ggplot2)
library(stringr)

# ---------------------------------------------------------
# 1. Create a species lookup table (specimen → species)
# ---------------------------------------------------------
species_map <- c(
  "30181"="Amanita bisporigera",
  "30182"="Amanita suballiacea",
  "30183"="Amanita oberwinkleriana",
  "30184"="Amanita suballiacea",
  "30185"="Amanita sp aurorae",
  "30186"="Amanita fusca",
  "30187"="Amanita suballiacea",
  "30188"="Amanita sp longicuneus",
  "30189"="Amanita rhacopus",
  "30190"="Amanita frostiana",
  "30191"="Amanita frostiana",
  "30192"="Amanita muscaria var guessowii",
  "30193"="Amanita albiceps",
  "30194"="Amanita sp 1",
  "30195"="Amanita amerivirosa",
  "30196"="Amanita muscaria var guessowii",
  "30197"="Amanita muscaria var guessowii",
  "30198"="Amanita mortenii",
  "30199"="Amanita bisporigera",
  "30201"="Amanita flavoconia",
  "30202"="Amanita porphyria",
  "30203"="Amanita amerivirosa",
  "30204"="Amanita amerivirosa",
  "30205"="Amanita flavoconia",
  "30206"="Amanita flavoconia",
  "30207"="Amanita porphyria",
  "30208"="Amanita lavendula",
  "30209"="Amanita amerivirosa",
  "30212"="Amanita firma",
  "30213"="Amanita sp cornelihybrida",
  "30214"="Amanita sp cornelihybrida",
  "30215"="Amanita sp. 61",
  "30221"="Amanita velatipes",
  "30222"="Amanita multisquamosa",
  "30226"="Amanita sp NY06",
  "30230"="Amanita rubescens var alba",
  "30238"="Amanita flavorubens",
  "30239"="Amanita virginiana",
  "30244"="Amanita coryli",
  "30249"="Amanita sp NY06",
  "30300"="Amanita firma", 
  "30295"="Amanita banningiana", 
  "30276"="Amanita sp 2", 
  "30274"="Amanita sp 3", 
  "30248"="Amanita brunnescens", 
  "30245"="Amanita fulva"
)

# ---------------------------------------------------------
# 2. Add species + section to the spore dataset
# ---------------------------------------------------------
all_spores2 <- all_spores %>%
  mutate(
    species = species_map[Sample],
    sectionid = group_map[Sample],
    species_short = str_replace(species, "^Amanita", "A.")
  )

# ---------------------------------------------------------
# 3. Sort species by section, then species name
# ---------------------------------------------------------
all_spores2 <- all_spores2 %>%
  arrange(sectionid, species_short) %>%
  mutate(species_short = factor(species_short, levels = unique(species_short)))

# ---------------------------------------------------------
# 4. Section color palette
# ---------------------------------------------------------
section_colors <- c(
  "Roanokensis"="magenta",
  "Phalloidae"="blue",
  "Vaginatae"="yellow",
  "Amanita"="red",
  "Validae"="green",
  "Ceasareae"="orange",
  "Amidella"="purple"
)

# ---------------------------------------------------------
# 5. Box-and-whisker plot (species-level, NO MEAN POINT)
# ---------------------------------------------------------
ggplot(all_spores2, aes(x = species_short, y = Length, fill = sectionid)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7, lwd = 0.4) +   # Q1–median–Q3 + whiskers
  scale_fill_manual(values = section_colors) +
  labs(
    title = "Basidiospore Length Distribution by Species",
    x = "Species",
    y = "Basidiospore Length (µm)",
    fill = "Section"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "italic")
  )

```

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
#ignore this one for now, use above

# ---------------------------------------------------------
# 0. Remove outlier row from specimen 30183
# ---------------------------------------------------------
spores30183 <- spores30183[-14, ]   # remove row 14

# ---------------------------------------------------------
# 1. Rebuild all_spores with corrected 30183
# ---------------------------------------------------------
all_spores <- rbind(
  spores30181, spores30182, spores30183, spores30184, spores30185,
  spores30186, spores30187, spores30188, spores30189, spores30190,
  spores30191, spores30192, spores30193, spores30194, spores30195,
  spores30196, spores30197, spores30198, spores30199, spores30201,
  spores30202, spores30203, spores30204, spores30205, spores30206,
  spores30207, spores30208, spores30209, spores30212, spores30213,
  spores30214, spores30215, spores30221, spores30222, spores30226,
  spores30230, spores30238, spores30239, spores30244, spores30249, 
)

# ---------------------------------------------------------
# 2. Species lookup table (specimen → species)
# ---------------------------------------------------------
species_map <- c(
  "30181"="Amanita bisporigera",
  "30182"="Amanita suballiacea",
  "30183"="Amanita oberwinkleriana",
  "30184"="Amanita suballiacea",
  "30185"="Amanita sp aurorae",
  "30186"="Amanita fusca",
  "30187"="Amanita suballiacea",
  "30188"="Amanita sp longicuneus",
  "30189"="Amanita rhacopus",
  "30190"="Amanita frostiana",
  "30191"="Amanita frostiana",
  "30192"="Amanita muscaria var guessowii",
  "30193"="Amanita albiceps",
  "30194"="Amanita sp 1",
  "30195"="Amanita amerivirosa",
  "30196"="Amanita muscaria var guessowii",
  "30197"="Amanita muscaria var guessowii",
  "30198"="Amanita mortenii",
  "30199"="Amanita bisporigera",
  "30201"="Amanita flavoconia",
  "30202"="Amanita porphyria",
  "30203"="Amanita amerivirosa",
  "30204"="Amanita amerivirosa",
  "30205"="Amanita flavoconia",
  "30206"="Amanita flavoconia",
  "30207"="Amanita porphyria",
  "30208"="Amanita lavendula",
  "30209"="Amanita amerivirosa",
  "30212"="Amanita firma",
  "30213"="Amanita sp cornelihybrida",
  "30214"="Amanita sp cornelihybrida",
  "30215"="Amanita sp. 61",
  "30221"="Amanita velatipes",
  "30222"="Amanita multisquamosa",
  "30226"="Amanita sp NY06",
  "30230"="Amanita rubescens var alba",
  "30238"="Amanita flavorubens",
  "30239"="Amanita virginiana",
  "30244"="Amanita coryli",
  "30249"="Amanita sp NY06",
  "30300"="Amanita firma", 
  "30295"="Amanita banningiana", 
  "30276"="Amanita sp 2", 
  "30274"="Amanita sp 3", 
  "30248"="Amanita brunnescens", 
  "30245"="Amanita fulva"
)

# ---------------------------------------------------------
# 3. Add species + section to the spore dataset
# ---------------------------------------------------------
all_spores2 <- all_spores %>%
  mutate(
    species = species_map[Sample],
    sectionid = group_map[Sample],
    species_short = str_replace(species, "^Amanita", "A.")
  )

# ---------------------------------------------------------
# 4. Sort species by section, then species name
# ---------------------------------------------------------
all_spores2 <- all_spores2 %>%
  arrange(sectionid, species_short) %>%
  mutate(species_short = factor(species_short, levels = unique(species_short)))

# ---------------------------------------------------------
# 5. Section color palette
# ---------------------------------------------------------
section_colors <- c(
  "Roanokensis"="magenta",
  "Phalloidae"="blue",
  "Vaginatae"="yellow",
  "Amanita"="red",
  "Validae"="green",
  "Ceasareae"="orange",
  "Amidella"="purple"
)

# ---------------------------------------------------------
# 6. Box-and-whisker plot (species-level, NO MEAN POINT)
# ---------------------------------------------------------
ggplot(all_spores2, aes(x = species_short, y = Length, fill = sectionid)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7, lwd = 0.3) +   # thinner lines
  scale_fill_manual(values = section_colors) +
  labs(
    title = "Basidiospore Length Distribution by Species",
    x = "Species",
    y = "Basidiospore Length (µm)",
    fill = "Section"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "italic")
  )

```

```{r}
library(dplyr)
library(ggplot2)
library(stringr)

# ---------------------------------------------------------
# 0. Remove outlier row from specimen 30183
# ---------------------------------------------------------
spores30183 <- spores30183[-14, ]   # remove row 14

# ---------------------------------------------------------
# 1. Rebuild all_spores with corrected 30183
# ---------------------------------------------------------
all_spores <- rbind(
  spores30181, spores30182, spores30183, spores30184, spores30185,
  spores30186, spores30187, spores30188, spores30189, spores30190,
  spores30191, spores30192, spores30193, spores30194, spores30195,
  spores30196, spores30197, spores30198, spores30199, spores30201,
  spores30202, spores30203, spores30204, spores30205, spores30206,
  spores30207, spores30208, spores30209, spores30212, spores30213,
  spores30214, spores30215, spores30221, spores30222, spores30226,
  spores30230, spores30238, spores30239, spores30244, spores30249
)

# ---------------------------------------------------------
# 2. Species lookup table (specimen → species)
# ---------------------------------------------------------
species_map <- c(
  "30181"="Amanita bisporigera",
  "30182"="Amanita suballiacea",
  "30183"="Amanita oberwinkleriana",
  "30184"="Amanita suballiacea",
  "30185"="Amanita sp aurorae",
  "30186"="Amanita fusca",
  "30187"="Amanita suballiacea",
  "30188"="Amanita sp longicuneus",
  "30189"="Amanita rhacopus",
  "30190"="Amanita frostiana",
  "30191"="Amanita frostiana",
  "30192"="Amanita muscaria var guessowii",
  "30193"="Amanita albiceps",
  "30194"="Amanita sp 1",
  "30195"="Amanita amerivirosa",
  "30196"="Amanita muscaria var guessowii",
  "30197"="Amanita muscaria var guessowii",
  "30198"="Amanita mortenii",
  "30199"="Amanita bisporigera",
  "30201"="Amanita flavoconia",
  "30202"="Amanita porphyria",
  "30203"="Amanita amerivirosa",
  "30204"="Amanita amerivirosa",
  "30205"="Amanita flavoconia",
  "30206"="Amanita flavoconia",
  "30207"="Amanita porphyria",
  "30208"="Amanita lavendula",
  "30209"="Amanita amerivirosa",
  "30212"="Amanita firma",
  "30213"="Amanita sp cornelihybrida",
  "30214"="Amanita sp cornelihybrida",
  "30215"="Amanita sp. 61",
  "30221"="Amanita velatipes",
  "30222"="Amanita multisquamosa",
  "30226"="Amanita sp NY06",
  "30230"="Amanita rubescens var alba",
  "30238"="Amanita flavorubens",
  "30239"="Amanita virginiana",
  "30244"="Amanita coryli",
  "30249"="Amanita sp NY06"
)

# ---------------------------------------------------------
# 3. Add species + section to the spore dataset
# ---------------------------------------------------------
all_spores2 <- all_spores %>%
  mutate(
    species = species_map[Sample],
    sectionid = group_map[Sample],
    species_short = str_replace(species, "^Amanita", "A.")
  )

# ---------------------------------------------------------
# 4. Sort species by section, then species name
# ---------------------------------------------------------
all_spores2 <- all_spores2 %>%
  arrange(sectionid, species_short) %>%
  mutate(species_short = factor(species_short, levels = unique(species_short)))

# ---------------------------------------------------------
# 5. Section color palette
# ---------------------------------------------------------
section_colors <- c(
  "Roanokensis"="magenta",
  "Phalloidae"="blue",
  "Vaginatae"="yellow",
  "Amanita"="red",
  "Validae"="green",
  "Ceasareae"="orange",
  "Amidella"="purple"
)

# ---------------------------------------------------------
# 6. Box-and-whisker plot (WIDTH, species-level, NO MEAN POINT)
# ---------------------------------------------------------
ggplot(all_spores2, aes(x = species_short, y = Width, fill = sectionid)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7, lwd = 0.3) +   # thinner lines
  scale_fill_manual(values = section_colors) +
  labs(
    title = "Basidiospore Width Distribution by Species",
    x = "Species",
    y = "Basidiospore Width (µm)",
    fill = "Section"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "italic")
  )

```

```{r}
library(dplyr)
library(ggplot2)
library(stringr)

# ---------------------------------------------------------
# 0. Remove outlier row from specimen 30183
# ---------------------------------------------------------
spores30183 <- spores30183[-14, ]   # remove row 14

# ---------------------------------------------------------
# 1. Rebuild all_spores with corrected 30183
# ---------------------------------------------------------
all_spores <- rbind(
  spores30181, spores30182, spores30183, spores30184, spores30185,
  spores30186, spores30187, spores30188, spores30189, spores30190,
  spores30191, spores30192, spores30193, spores30194, spores30195,
  spores30196, spores30197, spores30198, spores30199, spores30201,
  spores30202, spores30203, spores30204, spores30205, spores30206,
  spores30207, spores30208, spores30209, spores30212, spores30213,
  spores30214, spores30215, spores30221, spores30222, spores30226,
  spores30230, spores30238, spores30239, spores30244, spores30249
)

# ---------------------------------------------------------
# 2. Species lookup table (specimen → species)
# ---------------------------------------------------------
species_map <- c(
  "30181"="Amanita bisporigera",
  "30182"="Amanita suballiacea",
  "30183"="Amanita oberwinkleriana",
  "30184"="Amanita suballiacea",
  "30185"="Amanita sp aurorae",
  "30186"="Amanita fusca",
  "30187"="Amanita suballiacea",
  "30188"="Amanita sp longicuneus",
  "30189"="Amanita rhacopus",
  "30190"="Amanita frostiana",
  "30191"="Amanita frostiana",
  "30192"="Amanita muscaria var guessowii",
  "30193"="Amanita albiceps",
  "30194"="Amanita sp 1",
  "30195"="Amanita amerivirosa",
  "30196"="Amanita muscaria var guessowii",
  "30197"="Amanita muscaria var guessowii",
  "30198"="Amanita mortenii",
  "30199"="Amanita bisporigera",
  "30201"="Amanita flavoconia",
  "30202"="Amanita porphyria",
  "30203"="Amanita amerivirosa",
  "30204"="Amanita amerivirosa",
  "30205"="Amanita flavoconia",
  "30206"="Amanita flavoconia",
  "30207"="Amanita porphyria",
  "30208"="Amanita lavendula",
  "30209"="Amanita amerivirosa",
  "30212"="Amanita firma",
  "30213"="Amanita sp cornelihybrida",
  "30214"="Amanita sp cornelihybrida",
  "30215"="Amanita sp. 61",
  "30221"="Amanita velatipes",
  "30222"="Amanita multisquamosa",
  "30226"="Amanita sp NY06",
  "30230"="Amanita rubescens var alba",
  "30238"="Amanita flavorubens",
  "30239"="Amanita virginiana",
  "30244"="Amanita coryli",
  "30249"="Amanita sp NY06"
)

# ---------------------------------------------------------
# 3. Add species + section + rename Q column
# ---------------------------------------------------------
all_spores2 <- all_spores %>%
  mutate(
    species = species_map[Sample],
    sectionid = group_map[Sample],
    species_short = str_replace(species, "^Amanita", "A.")
  ) %>%
  rename(Q = Q..length.width.)   # <-- rename your Q column

# ---------------------------------------------------------
# 4. Sort species by section, then species name
# ---------------------------------------------------------
all_spores2 <- all_spores2 %>%
  arrange(sectionid, species_short) %>%
  mutate(species_short = factor(species_short, levels = unique(species_short)))

# ---------------------------------------------------------
# 5. Section color palette
# ---------------------------------------------------------
section_colors <- c(
  "Roanokensis"="magenta",
  "Phalloidae"="blue",
  "Vaginatae"="yellow",
  "Amanita"="red",
  "Validae"="green",
  "Ceasareae"="orange",
  "Amidella"="purple"
)

# ---------------------------------------------------------
# 6. Q box-and-whisker plot (NO MEAN POINT)
# ---------------------------------------------------------
ggplot(all_spores2, aes(x = species_short, y = Q, fill = sectionid)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7, lwd = 0.3) +
  scale_fill_manual(values = section_colors) +
  labs(
    title = "Basidiospore Q (Length ÷ Width) by Species",
    x = "Species",
    y = "Q Ratio",
    fill = "Section"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "italic")
  )

```

```{r}
ggplot(all_spores2, aes(x = species_short, y = Q, color = sectionid)) +
  geom_jitter(width = 0.2, alpha = 0.6, size = 1.8) +   # jittered points
  scale_color_manual(values = section_colors) +
  labs(
    title = "Individual Basidiospore Q Values by Species",
    x = "Species",
    y = "Q Ratio (Length ÷ Width)",
    color = "Section"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "italic")
  )

```

```{r}
ggplot(all_spores2, aes(x = Width, y = Length, color = sectionid)) +
  geom_jitter(width = 0.15, height = 0.15, alpha = 0.6, size = 1.8) +  # jittered points
  geom_abline(intercept = 0, slope = 1,
              color = "black", linetype = "dashed", linewidth = 0.7) + # Q = 1 line
  scale_color_manual(values = section_colors) +
  coord_cartesian(xlim = c(0, max(all_spores2$Width, na.rm = TRUE)),
                  ylim = c(0, max(all_spores2$Length, na.rm = TRUE))) +
  labs(
    title = "Basidiospore Length vs Width (with Q = 1 Reference Line)",
    x = "Width (µm)",
    y = "Length (µm)",
    color = "Section"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right"
  )


```

```{r}
# Ensure Q exists
all_spores$Q <- all_spores$Length / all_spores$Width

# Convert Group to factor
all_spores$Group <- as.factor(all_spores$Group)

# ---- 1. Check normality assumption (optional but useful) ----
library(ggplot2)

ggplot(all_spores, aes(x = Group, y = Q, fill = Group)) +
  geom_boxplot(alpha = 0.7) +
  theme_minimal() +
  labs(title = "Q Value Distribution by Section")

# ---- 2. ANOVA test ----
anova_model <- aov(Q ~ Group, data = all_spores)
summary(anova_model)   # <-- This gives the p-value for section differences

# ---- 3. Tukey post-hoc test ----
tukey_results <- TukeyHSD(anova_model)
tukey_results

# ---- 4. If ANOVA assumptions fail, use Kruskal-Wallis ----
kruskal.test(Q ~ Group, data = all_spores)

# ---- 5. Dunn post-hoc test for non-parametric ----
install.packages("FSA")
library(FSA)
dunnTest(Q ~ Group, data = all_spores, method = "bh")

```

